// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: CheckerMessage.proto

package com.nwchecker.server.utils.messages;

public final class CheckerMessageProto {
  private CheckerMessageProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface CheckerMessageOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // required int32 compilerId = 1;
    /**
     * <code>required int32 compilerId = 1;</code>
     */
    boolean hasCompilerId();
    /**
     * <code>required int32 compilerId = 1;</code>
     */
    int getCompilerId();

    // required bytes userSolution = 2;
    /**
     * <code>required bytes userSolution = 2;</code>
     */
    boolean hasUserSolution();
    /**
     * <code>required bytes userSolution = 2;</code>
     */
    com.google.protobuf.ByteString getUserSolution();

    // repeated .messages.CheckerMessage.DataPair inOutData = 3;
    /**
     * <code>repeated .messages.CheckerMessage.DataPair inOutData = 3;</code>
     */
    java.util.List<com.nwchecker.server.utils.messages.CheckerMessageProto.CheckerMessage.DataPair> 
        getInOutDataList();
    /**
     * <code>repeated .messages.CheckerMessage.DataPair inOutData = 3;</code>
     */
    com.nwchecker.server.utils.messages.CheckerMessageProto.CheckerMessage.DataPair getInOutData(int index);
    /**
     * <code>repeated .messages.CheckerMessage.DataPair inOutData = 3;</code>
     */
    int getInOutDataCount();
    /**
     * <code>repeated .messages.CheckerMessage.DataPair inOutData = 3;</code>
     */
    java.util.List<? extends com.nwchecker.server.utils.messages.CheckerMessageProto.CheckerMessage.DataPairOrBuilder> 
        getInOutDataOrBuilderList();
    /**
     * <code>repeated .messages.CheckerMessage.DataPair inOutData = 3;</code>
     */
    com.nwchecker.server.utils.messages.CheckerMessageProto.CheckerMessage.DataPairOrBuilder getInOutDataOrBuilder(
        int index);
  }
  /**
   * Protobuf type {@code messages.CheckerMessage}
   */
  public static final class CheckerMessage extends
      com.google.protobuf.GeneratedMessage
      implements CheckerMessageOrBuilder {
    // Use CheckerMessage.newBuilder() to construct.
    private CheckerMessage(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private CheckerMessage(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final CheckerMessage defaultInstance;
    public static CheckerMessage getDefaultInstance() {
      return defaultInstance;
    }

    public CheckerMessage getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private CheckerMessage(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              compilerId_ = input.readInt32();
              break;
            }
            case 18: {
              bitField0_ |= 0x00000002;
              userSolution_ = input.readBytes();
              break;
            }
            case 26: {
              if (!((mutable_bitField0_ & 0x00000004) == 0x00000004)) {
                inOutData_ = new java.util.ArrayList<com.nwchecker.server.utils.messages.CheckerMessageProto.CheckerMessage.DataPair>();
                mutable_bitField0_ |= 0x00000004;
              }
              inOutData_.add(input.readMessage(com.nwchecker.server.utils.messages.CheckerMessageProto.CheckerMessage.DataPair.PARSER, extensionRegistry));
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000004) == 0x00000004)) {
          inOutData_ = java.util.Collections.unmodifiableList(inOutData_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.nwchecker.server.utils.messages.CheckerMessageProto.internal_static_messages_CheckerMessage_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.nwchecker.server.utils.messages.CheckerMessageProto.internal_static_messages_CheckerMessage_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.nwchecker.server.utils.messages.CheckerMessageProto.CheckerMessage.class, com.nwchecker.server.utils.messages.CheckerMessageProto.CheckerMessage.Builder.class);
    }

    public static com.google.protobuf.Parser<CheckerMessage> PARSER =
        new com.google.protobuf.AbstractParser<CheckerMessage>() {
      public CheckerMessage parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new CheckerMessage(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<CheckerMessage> getParserForType() {
      return PARSER;
    }

    public interface DataPairOrBuilder
        extends com.google.protobuf.MessageOrBuilder {

      // required bytes inputData = 1;
      /**
       * <code>required bytes inputData = 1;</code>
       */
      boolean hasInputData();
      /**
       * <code>required bytes inputData = 1;</code>
       */
      com.google.protobuf.ByteString getInputData();

      // required bytes outputData = 2;
      /**
       * <code>required bytes outputData = 2;</code>
       */
      boolean hasOutputData();
      /**
       * <code>required bytes outputData = 2;</code>
       */
      com.google.protobuf.ByteString getOutputData();
    }
    /**
     * Protobuf type {@code messages.CheckerMessage.DataPair}
     */
    public static final class DataPair extends
        com.google.protobuf.GeneratedMessage
        implements DataPairOrBuilder {
      // Use DataPair.newBuilder() to construct.
      private DataPair(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
        super(builder);
        this.unknownFields = builder.getUnknownFields();
      }
      private DataPair(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

      private static final DataPair defaultInstance;
      public static DataPair getDefaultInstance() {
        return defaultInstance;
      }

      public DataPair getDefaultInstanceForType() {
        return defaultInstance;
      }

      private final com.google.protobuf.UnknownFieldSet unknownFields;
      @java.lang.Override
      public final com.google.protobuf.UnknownFieldSet
          getUnknownFields() {
        return this.unknownFields;
      }
      private DataPair(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        initFields();
        int mutable_bitField0_ = 0;
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
            com.google.protobuf.UnknownFieldSet.newBuilder();
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              default: {
                if (!parseUnknownField(input, unknownFields,
                                       extensionRegistry, tag)) {
                  done = true;
                }
                break;
              }
              case 10: {
                bitField0_ |= 0x00000001;
                inputData_ = input.readBytes();
                break;
              }
              case 18: {
                bitField0_ |= 0x00000002;
                outputData_ = input.readBytes();
                break;
              }
            }
          }
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(this);
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(
              e.getMessage()).setUnfinishedMessage(this);
        } finally {
          this.unknownFields = unknownFields.build();
          makeExtensionsImmutable();
        }
      }
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.nwchecker.server.utils.messages.CheckerMessageProto.internal_static_messages_CheckerMessage_DataPair_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.nwchecker.server.utils.messages.CheckerMessageProto.internal_static_messages_CheckerMessage_DataPair_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.nwchecker.server.utils.messages.CheckerMessageProto.CheckerMessage.DataPair.class, com.nwchecker.server.utils.messages.CheckerMessageProto.CheckerMessage.DataPair.Builder.class);
      }

      public static com.google.protobuf.Parser<DataPair> PARSER =
          new com.google.protobuf.AbstractParser<DataPair>() {
        public DataPair parsePartialFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
          return new DataPair(input, extensionRegistry);
        }
      };

      @java.lang.Override
      public com.google.protobuf.Parser<DataPair> getParserForType() {
        return PARSER;
      }

      private int bitField0_;
      // required bytes inputData = 1;
      public static final int INPUTDATA_FIELD_NUMBER = 1;
      private com.google.protobuf.ByteString inputData_;
      /**
       * <code>required bytes inputData = 1;</code>
       */
      public boolean hasInputData() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required bytes inputData = 1;</code>
       */
      public com.google.protobuf.ByteString getInputData() {
        return inputData_;
      }

      // required bytes outputData = 2;
      public static final int OUTPUTDATA_FIELD_NUMBER = 2;
      private com.google.protobuf.ByteString outputData_;
      /**
       * <code>required bytes outputData = 2;</code>
       */
      public boolean hasOutputData() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required bytes outputData = 2;</code>
       */
      public com.google.protobuf.ByteString getOutputData() {
        return outputData_;
      }

      private void initFields() {
        inputData_ = com.google.protobuf.ByteString.EMPTY;
        outputData_ = com.google.protobuf.ByteString.EMPTY;
      }
      private byte memoizedIsInitialized = -1;
      public final boolean isInitialized() {
        byte isInitialized = memoizedIsInitialized;
        if (isInitialized != -1) return isInitialized == 1;

        if (!hasInputData()) {
          memoizedIsInitialized = 0;
          return false;
        }
        if (!hasOutputData()) {
          memoizedIsInitialized = 0;
          return false;
        }
        memoizedIsInitialized = 1;
        return true;
      }

      public void writeTo(com.google.protobuf.CodedOutputStream output)
                          throws java.io.IOException {
        getSerializedSize();
        if (((bitField0_ & 0x00000001) == 0x00000001)) {
          output.writeBytes(1, inputData_);
        }
        if (((bitField0_ & 0x00000002) == 0x00000002)) {
          output.writeBytes(2, outputData_);
        }
        getUnknownFields().writeTo(output);
      }

      private int memoizedSerializedSize = -1;
      public int getSerializedSize() {
        int size = memoizedSerializedSize;
        if (size != -1) return size;

        size = 0;
        if (((bitField0_ & 0x00000001) == 0x00000001)) {
          size += com.google.protobuf.CodedOutputStream
            .computeBytesSize(1, inputData_);
        }
        if (((bitField0_ & 0x00000002) == 0x00000002)) {
          size += com.google.protobuf.CodedOutputStream
            .computeBytesSize(2, outputData_);
        }
        size += getUnknownFields().getSerializedSize();
        memoizedSerializedSize = size;
        return size;
      }

      private static final long serialVersionUID = 0L;
      @java.lang.Override
      protected java.lang.Object writeReplace()
          throws java.io.ObjectStreamException {
        return super.writeReplace();
      }

      public static com.nwchecker.server.utils.messages.CheckerMessageProto.CheckerMessage.DataPair parseFrom(
          com.google.protobuf.ByteString data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static com.nwchecker.server.utils.messages.CheckerMessageProto.CheckerMessage.DataPair parseFrom(
          com.google.protobuf.ByteString data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static com.nwchecker.server.utils.messages.CheckerMessageProto.CheckerMessage.DataPair parseFrom(byte[] data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static com.nwchecker.server.utils.messages.CheckerMessageProto.CheckerMessage.DataPair parseFrom(
          byte[] data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static com.nwchecker.server.utils.messages.CheckerMessageProto.CheckerMessage.DataPair parseFrom(java.io.InputStream input)
          throws java.io.IOException {
        return PARSER.parseFrom(input);
      }
      public static com.nwchecker.server.utils.messages.CheckerMessageProto.CheckerMessage.DataPair parseFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return PARSER.parseFrom(input, extensionRegistry);
      }
      public static com.nwchecker.server.utils.messages.CheckerMessageProto.CheckerMessage.DataPair parseDelimitedFrom(java.io.InputStream input)
          throws java.io.IOException {
        return PARSER.parseDelimitedFrom(input);
      }
      public static com.nwchecker.server.utils.messages.CheckerMessageProto.CheckerMessage.DataPair parseDelimitedFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return PARSER.parseDelimitedFrom(input, extensionRegistry);
      }
      public static com.nwchecker.server.utils.messages.CheckerMessageProto.CheckerMessage.DataPair parseFrom(
          com.google.protobuf.CodedInputStream input)
          throws java.io.IOException {
        return PARSER.parseFrom(input);
      }
      public static com.nwchecker.server.utils.messages.CheckerMessageProto.CheckerMessage.DataPair parseFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return PARSER.parseFrom(input, extensionRegistry);
      }

      public static Builder newBuilder() { return Builder.create(); }
      public Builder newBuilderForType() { return newBuilder(); }
      public static Builder newBuilder(com.nwchecker.server.utils.messages.CheckerMessageProto.CheckerMessage.DataPair prototype) {
        return newBuilder().mergeFrom(prototype);
      }
      public Builder toBuilder() { return newBuilder(this); }

      @java.lang.Override
      protected Builder newBuilderForType(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        Builder builder = new Builder(parent);
        return builder;
      }
      /**
       * Protobuf type {@code messages.CheckerMessage.DataPair}
       */
      public static final class Builder extends
          com.google.protobuf.GeneratedMessage.Builder<Builder>
         implements com.nwchecker.server.utils.messages.CheckerMessageProto.CheckerMessage.DataPairOrBuilder {
        public static final com.google.protobuf.Descriptors.Descriptor
            getDescriptor() {
          return com.nwchecker.server.utils.messages.CheckerMessageProto.internal_static_messages_CheckerMessage_DataPair_descriptor;
        }

        protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
            internalGetFieldAccessorTable() {
          return com.nwchecker.server.utils.messages.CheckerMessageProto.internal_static_messages_CheckerMessage_DataPair_fieldAccessorTable
              .ensureFieldAccessorsInitialized(
                  com.nwchecker.server.utils.messages.CheckerMessageProto.CheckerMessage.DataPair.class, com.nwchecker.server.utils.messages.CheckerMessageProto.CheckerMessage.DataPair.Builder.class);
        }

        // Construct using com.nwchecker.server.utils.messages.CheckerMessageProto.CheckerMessage.DataPair.newBuilder()
        private Builder() {
          maybeForceBuilderInitialization();
        }

        private Builder(
            com.google.protobuf.GeneratedMessage.BuilderParent parent) {
          super(parent);
          maybeForceBuilderInitialization();
        }
        private void maybeForceBuilderInitialization() {
          if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          }
        }
        private static Builder create() {
          return new Builder();
        }

        public Builder clear() {
          super.clear();
          inputData_ = com.google.protobuf.ByteString.EMPTY;
          bitField0_ = (bitField0_ & ~0x00000001);
          outputData_ = com.google.protobuf.ByteString.EMPTY;
          bitField0_ = (bitField0_ & ~0x00000002);
          return this;
        }

        public Builder clone() {
          return create().mergeFrom(buildPartial());
        }

        public com.google.protobuf.Descriptors.Descriptor
            getDescriptorForType() {
          return com.nwchecker.server.utils.messages.CheckerMessageProto.internal_static_messages_CheckerMessage_DataPair_descriptor;
        }

        public com.nwchecker.server.utils.messages.CheckerMessageProto.CheckerMessage.DataPair getDefaultInstanceForType() {
          return com.nwchecker.server.utils.messages.CheckerMessageProto.CheckerMessage.DataPair.getDefaultInstance();
        }

        public com.nwchecker.server.utils.messages.CheckerMessageProto.CheckerMessage.DataPair build() {
          com.nwchecker.server.utils.messages.CheckerMessageProto.CheckerMessage.DataPair result = buildPartial();
          if (!result.isInitialized()) {
            throw newUninitializedMessageException(result);
          }
          return result;
        }

        public com.nwchecker.server.utils.messages.CheckerMessageProto.CheckerMessage.DataPair buildPartial() {
          com.nwchecker.server.utils.messages.CheckerMessageProto.CheckerMessage.DataPair result = new com.nwchecker.server.utils.messages.CheckerMessageProto.CheckerMessage.DataPair(this);
          int from_bitField0_ = bitField0_;
          int to_bitField0_ = 0;
          if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
            to_bitField0_ |= 0x00000001;
          }
          result.inputData_ = inputData_;
          if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
            to_bitField0_ |= 0x00000002;
          }
          result.outputData_ = outputData_;
          result.bitField0_ = to_bitField0_;
          onBuilt();
          return result;
        }

        public Builder mergeFrom(com.google.protobuf.Message other) {
          if (other instanceof com.nwchecker.server.utils.messages.CheckerMessageProto.CheckerMessage.DataPair) {
            return mergeFrom((com.nwchecker.server.utils.messages.CheckerMessageProto.CheckerMessage.DataPair)other);
          } else {
            super.mergeFrom(other);
            return this;
          }
        }

        public Builder mergeFrom(com.nwchecker.server.utils.messages.CheckerMessageProto.CheckerMessage.DataPair other) {
          if (other == com.nwchecker.server.utils.messages.CheckerMessageProto.CheckerMessage.DataPair.getDefaultInstance()) return this;
          if (other.hasInputData()) {
            setInputData(other.getInputData());
          }
          if (other.hasOutputData()) {
            setOutputData(other.getOutputData());
          }
          this.mergeUnknownFields(other.getUnknownFields());
          return this;
        }

        public final boolean isInitialized() {
          if (!hasInputData()) {
            
            return false;
          }
          if (!hasOutputData()) {
            
            return false;
          }
          return true;
        }

        public Builder mergeFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
          com.nwchecker.server.utils.messages.CheckerMessageProto.CheckerMessage.DataPair parsedMessage = null;
          try {
            parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
          } catch (com.google.protobuf.InvalidProtocolBufferException e) {
            parsedMessage = (com.nwchecker.server.utils.messages.CheckerMessageProto.CheckerMessage.DataPair) e.getUnfinishedMessage();
            throw e;
          } finally {
            if (parsedMessage != null) {
              mergeFrom(parsedMessage);
            }
          }
          return this;
        }
        private int bitField0_;

        // required bytes inputData = 1;
        private com.google.protobuf.ByteString inputData_ = com.google.protobuf.ByteString.EMPTY;
        /**
         * <code>required bytes inputData = 1;</code>
         */
        public boolean hasInputData() {
          return ((bitField0_ & 0x00000001) == 0x00000001);
        }
        /**
         * <code>required bytes inputData = 1;</code>
         */
        public com.google.protobuf.ByteString getInputData() {
          return inputData_;
        }
        /**
         * <code>required bytes inputData = 1;</code>
         */
        public Builder setInputData(com.google.protobuf.ByteString value) {
          if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
          inputData_ = value;
          onChanged();
          return this;
        }
        /**
         * <code>required bytes inputData = 1;</code>
         */
        public Builder clearInputData() {
          bitField0_ = (bitField0_ & ~0x00000001);
          inputData_ = getDefaultInstance().getInputData();
          onChanged();
          return this;
        }

        // required bytes outputData = 2;
        private com.google.protobuf.ByteString outputData_ = com.google.protobuf.ByteString.EMPTY;
        /**
         * <code>required bytes outputData = 2;</code>
         */
        public boolean hasOutputData() {
          return ((bitField0_ & 0x00000002) == 0x00000002);
        }
        /**
         * <code>required bytes outputData = 2;</code>
         */
        public com.google.protobuf.ByteString getOutputData() {
          return outputData_;
        }
        /**
         * <code>required bytes outputData = 2;</code>
         */
        public Builder setOutputData(com.google.protobuf.ByteString value) {
          if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
          outputData_ = value;
          onChanged();
          return this;
        }
        /**
         * <code>required bytes outputData = 2;</code>
         */
        public Builder clearOutputData() {
          bitField0_ = (bitField0_ & ~0x00000002);
          outputData_ = getDefaultInstance().getOutputData();
          onChanged();
          return this;
        }

        // @@protoc_insertion_point(builder_scope:messages.CheckerMessage.DataPair)
      }

      static {
        defaultInstance = new DataPair(true);
        defaultInstance.initFields();
      }

      // @@protoc_insertion_point(class_scope:messages.CheckerMessage.DataPair)
    }

    private int bitField0_;
    // required int32 compilerId = 1;
    public static final int COMPILERID_FIELD_NUMBER = 1;
    private int compilerId_;
    /**
     * <code>required int32 compilerId = 1;</code>
     */
    public boolean hasCompilerId() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required int32 compilerId = 1;</code>
     */
    public int getCompilerId() {
      return compilerId_;
    }

    // required bytes userSolution = 2;
    public static final int USERSOLUTION_FIELD_NUMBER = 2;
    private com.google.protobuf.ByteString userSolution_;
    /**
     * <code>required bytes userSolution = 2;</code>
     */
    public boolean hasUserSolution() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>required bytes userSolution = 2;</code>
     */
    public com.google.protobuf.ByteString getUserSolution() {
      return userSolution_;
    }

    // repeated .messages.CheckerMessage.DataPair inOutData = 3;
    public static final int INOUTDATA_FIELD_NUMBER = 3;
    private java.util.List<com.nwchecker.server.utils.messages.CheckerMessageProto.CheckerMessage.DataPair> inOutData_;
    /**
     * <code>repeated .messages.CheckerMessage.DataPair inOutData = 3;</code>
     */
    public java.util.List<com.nwchecker.server.utils.messages.CheckerMessageProto.CheckerMessage.DataPair> getInOutDataList() {
      return inOutData_;
    }
    /**
     * <code>repeated .messages.CheckerMessage.DataPair inOutData = 3;</code>
     */
    public java.util.List<? extends com.nwchecker.server.utils.messages.CheckerMessageProto.CheckerMessage.DataPairOrBuilder> 
        getInOutDataOrBuilderList() {
      return inOutData_;
    }
    /**
     * <code>repeated .messages.CheckerMessage.DataPair inOutData = 3;</code>
     */
    public int getInOutDataCount() {
      return inOutData_.size();
    }
    /**
     * <code>repeated .messages.CheckerMessage.DataPair inOutData = 3;</code>
     */
    public com.nwchecker.server.utils.messages.CheckerMessageProto.CheckerMessage.DataPair getInOutData(int index) {
      return inOutData_.get(index);
    }
    /**
     * <code>repeated .messages.CheckerMessage.DataPair inOutData = 3;</code>
     */
    public com.nwchecker.server.utils.messages.CheckerMessageProto.CheckerMessage.DataPairOrBuilder getInOutDataOrBuilder(
        int index) {
      return inOutData_.get(index);
    }

    private void initFields() {
      compilerId_ = 0;
      userSolution_ = com.google.protobuf.ByteString.EMPTY;
      inOutData_ = java.util.Collections.emptyList();
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      if (!hasCompilerId()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasUserSolution()) {
        memoizedIsInitialized = 0;
        return false;
      }
      for (int i = 0; i < getInOutDataCount(); i++) {
        if (!getInOutData(i).isInitialized()) {
          memoizedIsInitialized = 0;
          return false;
        }
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt32(1, compilerId_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeBytes(2, userSolution_);
      }
      for (int i = 0; i < inOutData_.size(); i++) {
        output.writeMessage(3, inOutData_.get(i));
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, compilerId_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, userSolution_);
      }
      for (int i = 0; i < inOutData_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(3, inOutData_.get(i));
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static com.nwchecker.server.utils.messages.CheckerMessageProto.CheckerMessage parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.nwchecker.server.utils.messages.CheckerMessageProto.CheckerMessage parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.nwchecker.server.utils.messages.CheckerMessageProto.CheckerMessage parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.nwchecker.server.utils.messages.CheckerMessageProto.CheckerMessage parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.nwchecker.server.utils.messages.CheckerMessageProto.CheckerMessage parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.nwchecker.server.utils.messages.CheckerMessageProto.CheckerMessage parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.nwchecker.server.utils.messages.CheckerMessageProto.CheckerMessage parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.nwchecker.server.utils.messages.CheckerMessageProto.CheckerMessage parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.nwchecker.server.utils.messages.CheckerMessageProto.CheckerMessage parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.nwchecker.server.utils.messages.CheckerMessageProto.CheckerMessage parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.nwchecker.server.utils.messages.CheckerMessageProto.CheckerMessage prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code messages.CheckerMessage}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements com.nwchecker.server.utils.messages.CheckerMessageProto.CheckerMessageOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.nwchecker.server.utils.messages.CheckerMessageProto.internal_static_messages_CheckerMessage_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.nwchecker.server.utils.messages.CheckerMessageProto.internal_static_messages_CheckerMessage_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.nwchecker.server.utils.messages.CheckerMessageProto.CheckerMessage.class, com.nwchecker.server.utils.messages.CheckerMessageProto.CheckerMessage.Builder.class);
      }

      // Construct using com.nwchecker.server.utils.messages.CheckerMessageProto.CheckerMessage.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          getInOutDataFieldBuilder();
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        compilerId_ = 0;
        bitField0_ = (bitField0_ & ~0x00000001);
        userSolution_ = com.google.protobuf.ByteString.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000002);
        if (inOutDataBuilder_ == null) {
          inOutData_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000004);
        } else {
          inOutDataBuilder_.clear();
        }
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.nwchecker.server.utils.messages.CheckerMessageProto.internal_static_messages_CheckerMessage_descriptor;
      }

      public com.nwchecker.server.utils.messages.CheckerMessageProto.CheckerMessage getDefaultInstanceForType() {
        return com.nwchecker.server.utils.messages.CheckerMessageProto.CheckerMessage.getDefaultInstance();
      }

      public com.nwchecker.server.utils.messages.CheckerMessageProto.CheckerMessage build() {
        com.nwchecker.server.utils.messages.CheckerMessageProto.CheckerMessage result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.nwchecker.server.utils.messages.CheckerMessageProto.CheckerMessage buildPartial() {
        com.nwchecker.server.utils.messages.CheckerMessageProto.CheckerMessage result = new com.nwchecker.server.utils.messages.CheckerMessageProto.CheckerMessage(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.compilerId_ = compilerId_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.userSolution_ = userSolution_;
        if (inOutDataBuilder_ == null) {
          if (((bitField0_ & 0x00000004) == 0x00000004)) {
            inOutData_ = java.util.Collections.unmodifiableList(inOutData_);
            bitField0_ = (bitField0_ & ~0x00000004);
          }
          result.inOutData_ = inOutData_;
        } else {
          result.inOutData_ = inOutDataBuilder_.build();
        }
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.nwchecker.server.utils.messages.CheckerMessageProto.CheckerMessage) {
          return mergeFrom((com.nwchecker.server.utils.messages.CheckerMessageProto.CheckerMessage)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.nwchecker.server.utils.messages.CheckerMessageProto.CheckerMessage other) {
        if (other == com.nwchecker.server.utils.messages.CheckerMessageProto.CheckerMessage.getDefaultInstance()) return this;
        if (other.hasCompilerId()) {
          setCompilerId(other.getCompilerId());
        }
        if (other.hasUserSolution()) {
          setUserSolution(other.getUserSolution());
        }
        if (inOutDataBuilder_ == null) {
          if (!other.inOutData_.isEmpty()) {
            if (inOutData_.isEmpty()) {
              inOutData_ = other.inOutData_;
              bitField0_ = (bitField0_ & ~0x00000004);
            } else {
              ensureInOutDataIsMutable();
              inOutData_.addAll(other.inOutData_);
            }
            onChanged();
          }
        } else {
          if (!other.inOutData_.isEmpty()) {
            if (inOutDataBuilder_.isEmpty()) {
              inOutDataBuilder_.dispose();
              inOutDataBuilder_ = null;
              inOutData_ = other.inOutData_;
              bitField0_ = (bitField0_ & ~0x00000004);
              inOutDataBuilder_ = 
                com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                   getInOutDataFieldBuilder() : null;
            } else {
              inOutDataBuilder_.addAllMessages(other.inOutData_);
            }
          }
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasCompilerId()) {
          
          return false;
        }
        if (!hasUserSolution()) {
          
          return false;
        }
        for (int i = 0; i < getInOutDataCount(); i++) {
          if (!getInOutData(i).isInitialized()) {
            
            return false;
          }
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.nwchecker.server.utils.messages.CheckerMessageProto.CheckerMessage parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.nwchecker.server.utils.messages.CheckerMessageProto.CheckerMessage) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // required int32 compilerId = 1;
      private int compilerId_ ;
      /**
       * <code>required int32 compilerId = 1;</code>
       */
      public boolean hasCompilerId() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required int32 compilerId = 1;</code>
       */
      public int getCompilerId() {
        return compilerId_;
      }
      /**
       * <code>required int32 compilerId = 1;</code>
       */
      public Builder setCompilerId(int value) {
        bitField0_ |= 0x00000001;
        compilerId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 compilerId = 1;</code>
       */
      public Builder clearCompilerId() {
        bitField0_ = (bitField0_ & ~0x00000001);
        compilerId_ = 0;
        onChanged();
        return this;
      }

      // required bytes userSolution = 2;
      private com.google.protobuf.ByteString userSolution_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <code>required bytes userSolution = 2;</code>
       */
      public boolean hasUserSolution() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required bytes userSolution = 2;</code>
       */
      public com.google.protobuf.ByteString getUserSolution() {
        return userSolution_;
      }
      /**
       * <code>required bytes userSolution = 2;</code>
       */
      public Builder setUserSolution(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        userSolution_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required bytes userSolution = 2;</code>
       */
      public Builder clearUserSolution() {
        bitField0_ = (bitField0_ & ~0x00000002);
        userSolution_ = getDefaultInstance().getUserSolution();
        onChanged();
        return this;
      }

      // repeated .messages.CheckerMessage.DataPair inOutData = 3;
      private java.util.List<com.nwchecker.server.utils.messages.CheckerMessageProto.CheckerMessage.DataPair> inOutData_ =
        java.util.Collections.emptyList();
      private void ensureInOutDataIsMutable() {
        if (!((bitField0_ & 0x00000004) == 0x00000004)) {
          inOutData_ = new java.util.ArrayList<com.nwchecker.server.utils.messages.CheckerMessageProto.CheckerMessage.DataPair>(inOutData_);
          bitField0_ |= 0x00000004;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilder<
          com.nwchecker.server.utils.messages.CheckerMessageProto.CheckerMessage.DataPair, com.nwchecker.server.utils.messages.CheckerMessageProto.CheckerMessage.DataPair.Builder, com.nwchecker.server.utils.messages.CheckerMessageProto.CheckerMessage.DataPairOrBuilder> inOutDataBuilder_;

      /**
       * <code>repeated .messages.CheckerMessage.DataPair inOutData = 3;</code>
       */
      public java.util.List<com.nwchecker.server.utils.messages.CheckerMessageProto.CheckerMessage.DataPair> getInOutDataList() {
        if (inOutDataBuilder_ == null) {
          return java.util.Collections.unmodifiableList(inOutData_);
        } else {
          return inOutDataBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .messages.CheckerMessage.DataPair inOutData = 3;</code>
       */
      public int getInOutDataCount() {
        if (inOutDataBuilder_ == null) {
          return inOutData_.size();
        } else {
          return inOutDataBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .messages.CheckerMessage.DataPair inOutData = 3;</code>
       */
      public com.nwchecker.server.utils.messages.CheckerMessageProto.CheckerMessage.DataPair getInOutData(int index) {
        if (inOutDataBuilder_ == null) {
          return inOutData_.get(index);
        } else {
          return inOutDataBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .messages.CheckerMessage.DataPair inOutData = 3;</code>
       */
      public Builder setInOutData(
          int index, com.nwchecker.server.utils.messages.CheckerMessageProto.CheckerMessage.DataPair value) {
        if (inOutDataBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureInOutDataIsMutable();
          inOutData_.set(index, value);
          onChanged();
        } else {
          inOutDataBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .messages.CheckerMessage.DataPair inOutData = 3;</code>
       */
      public Builder setInOutData(
          int index, com.nwchecker.server.utils.messages.CheckerMessageProto.CheckerMessage.DataPair.Builder builderForValue) {
        if (inOutDataBuilder_ == null) {
          ensureInOutDataIsMutable();
          inOutData_.set(index, builderForValue.build());
          onChanged();
        } else {
          inOutDataBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .messages.CheckerMessage.DataPair inOutData = 3;</code>
       */
      public Builder addInOutData(com.nwchecker.server.utils.messages.CheckerMessageProto.CheckerMessage.DataPair value) {
        if (inOutDataBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureInOutDataIsMutable();
          inOutData_.add(value);
          onChanged();
        } else {
          inOutDataBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .messages.CheckerMessage.DataPair inOutData = 3;</code>
       */
      public Builder addInOutData(
          int index, com.nwchecker.server.utils.messages.CheckerMessageProto.CheckerMessage.DataPair value) {
        if (inOutDataBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureInOutDataIsMutable();
          inOutData_.add(index, value);
          onChanged();
        } else {
          inOutDataBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .messages.CheckerMessage.DataPair inOutData = 3;</code>
       */
      public Builder addInOutData(
          com.nwchecker.server.utils.messages.CheckerMessageProto.CheckerMessage.DataPair.Builder builderForValue) {
        if (inOutDataBuilder_ == null) {
          ensureInOutDataIsMutable();
          inOutData_.add(builderForValue.build());
          onChanged();
        } else {
          inOutDataBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .messages.CheckerMessage.DataPair inOutData = 3;</code>
       */
      public Builder addInOutData(
          int index, com.nwchecker.server.utils.messages.CheckerMessageProto.CheckerMessage.DataPair.Builder builderForValue) {
        if (inOutDataBuilder_ == null) {
          ensureInOutDataIsMutable();
          inOutData_.add(index, builderForValue.build());
          onChanged();
        } else {
          inOutDataBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .messages.CheckerMessage.DataPair inOutData = 3;</code>
       */
      public Builder addAllInOutData(
          java.lang.Iterable<? extends com.nwchecker.server.utils.messages.CheckerMessageProto.CheckerMessage.DataPair> values) {
        if (inOutDataBuilder_ == null) {
          ensureInOutDataIsMutable();
          super.addAll(values, inOutData_);
          onChanged();
        } else {
          inOutDataBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .messages.CheckerMessage.DataPair inOutData = 3;</code>
       */
      public Builder clearInOutData() {
        if (inOutDataBuilder_ == null) {
          inOutData_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000004);
          onChanged();
        } else {
          inOutDataBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .messages.CheckerMessage.DataPair inOutData = 3;</code>
       */
      public Builder removeInOutData(int index) {
        if (inOutDataBuilder_ == null) {
          ensureInOutDataIsMutable();
          inOutData_.remove(index);
          onChanged();
        } else {
          inOutDataBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .messages.CheckerMessage.DataPair inOutData = 3;</code>
       */
      public com.nwchecker.server.utils.messages.CheckerMessageProto.CheckerMessage.DataPair.Builder getInOutDataBuilder(
          int index) {
        return getInOutDataFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .messages.CheckerMessage.DataPair inOutData = 3;</code>
       */
      public com.nwchecker.server.utils.messages.CheckerMessageProto.CheckerMessage.DataPairOrBuilder getInOutDataOrBuilder(
          int index) {
        if (inOutDataBuilder_ == null) {
          return inOutData_.get(index);  } else {
          return inOutDataBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .messages.CheckerMessage.DataPair inOutData = 3;</code>
       */
      public java.util.List<? extends com.nwchecker.server.utils.messages.CheckerMessageProto.CheckerMessage.DataPairOrBuilder> 
           getInOutDataOrBuilderList() {
        if (inOutDataBuilder_ != null) {
          return inOutDataBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(inOutData_);
        }
      }
      /**
       * <code>repeated .messages.CheckerMessage.DataPair inOutData = 3;</code>
       */
      public com.nwchecker.server.utils.messages.CheckerMessageProto.CheckerMessage.DataPair.Builder addInOutDataBuilder() {
        return getInOutDataFieldBuilder().addBuilder(
            com.nwchecker.server.utils.messages.CheckerMessageProto.CheckerMessage.DataPair.getDefaultInstance());
      }
      /**
       * <code>repeated .messages.CheckerMessage.DataPair inOutData = 3;</code>
       */
      public com.nwchecker.server.utils.messages.CheckerMessageProto.CheckerMessage.DataPair.Builder addInOutDataBuilder(
          int index) {
        return getInOutDataFieldBuilder().addBuilder(
            index, com.nwchecker.server.utils.messages.CheckerMessageProto.CheckerMessage.DataPair.getDefaultInstance());
      }
      /**
       * <code>repeated .messages.CheckerMessage.DataPair inOutData = 3;</code>
       */
      public java.util.List<com.nwchecker.server.utils.messages.CheckerMessageProto.CheckerMessage.DataPair.Builder> 
           getInOutDataBuilderList() {
        return getInOutDataFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilder<
          com.nwchecker.server.utils.messages.CheckerMessageProto.CheckerMessage.DataPair, com.nwchecker.server.utils.messages.CheckerMessageProto.CheckerMessage.DataPair.Builder, com.nwchecker.server.utils.messages.CheckerMessageProto.CheckerMessage.DataPairOrBuilder> 
          getInOutDataFieldBuilder() {
        if (inOutDataBuilder_ == null) {
          inOutDataBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
              com.nwchecker.server.utils.messages.CheckerMessageProto.CheckerMessage.DataPair, com.nwchecker.server.utils.messages.CheckerMessageProto.CheckerMessage.DataPair.Builder, com.nwchecker.server.utils.messages.CheckerMessageProto.CheckerMessage.DataPairOrBuilder>(
                  inOutData_,
                  ((bitField0_ & 0x00000004) == 0x00000004),
                  getParentForChildren(),
                  isClean());
          inOutData_ = null;
        }
        return inOutDataBuilder_;
      }

      // @@protoc_insertion_point(builder_scope:messages.CheckerMessage)
    }

    static {
      defaultInstance = new CheckerMessage(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:messages.CheckerMessage)
  }

  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_messages_CheckerMessage_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_messages_CheckerMessage_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_messages_CheckerMessage_DataPair_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_messages_CheckerMessage_DataPair_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\024CheckerMessage.proto\022\010messages\"\243\001\n\016Che" +
      "ckerMessage\022\022\n\ncompilerId\030\001 \002(\005\022\024\n\014userS" +
      "olution\030\002 \002(\014\0224\n\tinOutData\030\003 \003(\0132!.messa" +
      "ges.CheckerMessage.DataPair\0321\n\010DataPair\022" +
      "\021\n\tinputData\030\001 \002(\014\022\022\n\noutputData\030\002 \002(\014B:" +
      "\n#com.nwchecker.server.utils.messagesB\023C" +
      "heckerMessageProto"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_messages_CheckerMessage_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_messages_CheckerMessage_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_messages_CheckerMessage_descriptor,
              new java.lang.String[] { "CompilerId", "UserSolution", "InOutData", });
          internal_static_messages_CheckerMessage_DataPair_descriptor =
            internal_static_messages_CheckerMessage_descriptor.getNestedTypes().get(0);
          internal_static_messages_CheckerMessage_DataPair_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_messages_CheckerMessage_DataPair_descriptor,
              new java.lang.String[] { "InputData", "OutputData", });
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }

  // @@protoc_insertion_point(outer_class_scope)
}
