// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: CheckerResponse.proto

package com.nwchecker.server.utils.messages;

public final class CheckerResponseProto {
  private CheckerResponseProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface CheckerResponseOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // repeated .messages.CheckerResponse.AtomicResponse testData = 1;
    /**
     * <code>repeated .messages.CheckerResponse.AtomicResponse testData = 1;</code>
     */
    java.util.List<com.nwchecker.server.utils.messages.CheckerResponseProto.CheckerResponse.AtomicResponse> 
        getTestDataList();
    /**
     * <code>repeated .messages.CheckerResponse.AtomicResponse testData = 1;</code>
     */
    com.nwchecker.server.utils.messages.CheckerResponseProto.CheckerResponse.AtomicResponse getTestData(int index);
    /**
     * <code>repeated .messages.CheckerResponse.AtomicResponse testData = 1;</code>
     */
    int getTestDataCount();
    /**
     * <code>repeated .messages.CheckerResponse.AtomicResponse testData = 1;</code>
     */
    java.util.List<? extends com.nwchecker.server.utils.messages.CheckerResponseProto.CheckerResponse.AtomicResponseOrBuilder> 
        getTestDataOrBuilderList();
    /**
     * <code>repeated .messages.CheckerResponse.AtomicResponse testData = 1;</code>
     */
    com.nwchecker.server.utils.messages.CheckerResponseProto.CheckerResponse.AtomicResponseOrBuilder getTestDataOrBuilder(
        int index);
  }
  /**
   * Protobuf type {@code messages.CheckerResponse}
   */
  public static final class CheckerResponse extends
      com.google.protobuf.GeneratedMessage
      implements CheckerResponseOrBuilder {
    // Use CheckerResponse.newBuilder() to construct.
    private CheckerResponse(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private CheckerResponse(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final CheckerResponse defaultInstance;
    public static CheckerResponse getDefaultInstance() {
      return defaultInstance;
    }

    public CheckerResponse getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private CheckerResponse(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              if (!((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
                testData_ = new java.util.ArrayList<com.nwchecker.server.utils.messages.CheckerResponseProto.CheckerResponse.AtomicResponse>();
                mutable_bitField0_ |= 0x00000001;
              }
              testData_.add(input.readMessage(com.nwchecker.server.utils.messages.CheckerResponseProto.CheckerResponse.AtomicResponse.PARSER, extensionRegistry));
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
          testData_ = java.util.Collections.unmodifiableList(testData_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.nwchecker.server.utils.messages.CheckerResponseProto.internal_static_messages_CheckerResponse_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.nwchecker.server.utils.messages.CheckerResponseProto.internal_static_messages_CheckerResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.nwchecker.server.utils.messages.CheckerResponseProto.CheckerResponse.class, com.nwchecker.server.utils.messages.CheckerResponseProto.CheckerResponse.Builder.class);
    }

    public static com.google.protobuf.Parser<CheckerResponse> PARSER =
        new com.google.protobuf.AbstractParser<CheckerResponse>() {
      public CheckerResponse parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new CheckerResponse(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<CheckerResponse> getParserForType() {
      return PARSER;
    }

    public interface AtomicResponseOrBuilder
        extends com.google.protobuf.MessageOrBuilder {

      // required int32 success = 1;
      /**
       * <code>required int32 success = 1;</code>
       */
      boolean hasSuccess();
      /**
       * <code>required int32 success = 1;</code>
       */
      int getSuccess();

      // required int32 executionTime = 2;
      /**
       * <code>required int32 executionTime = 2;</code>
       */
      boolean hasExecutionTime();
      /**
       * <code>required int32 executionTime = 2;</code>
       */
      int getExecutionTime();

      // required int32 memoryUsed = 3;
      /**
       * <code>required int32 memoryUsed = 3;</code>
       */
      boolean hasMemoryUsed();
      /**
       * <code>required int32 memoryUsed = 3;</code>
       */
      int getMemoryUsed();
    }
    /**
     * Protobuf type {@code messages.CheckerResponse.AtomicResponse}
     */
    public static final class AtomicResponse extends
        com.google.protobuf.GeneratedMessage
        implements AtomicResponseOrBuilder {
      // Use AtomicResponse.newBuilder() to construct.
      private AtomicResponse(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
        super(builder);
        this.unknownFields = builder.getUnknownFields();
      }
      private AtomicResponse(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

      private static final AtomicResponse defaultInstance;
      public static AtomicResponse getDefaultInstance() {
        return defaultInstance;
      }

      public AtomicResponse getDefaultInstanceForType() {
        return defaultInstance;
      }

      private final com.google.protobuf.UnknownFieldSet unknownFields;
      @java.lang.Override
      public final com.google.protobuf.UnknownFieldSet
          getUnknownFields() {
        return this.unknownFields;
      }
      private AtomicResponse(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        initFields();
        int mutable_bitField0_ = 0;
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
            com.google.protobuf.UnknownFieldSet.newBuilder();
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              default: {
                if (!parseUnknownField(input, unknownFields,
                                       extensionRegistry, tag)) {
                  done = true;
                }
                break;
              }
              case 8: {
                bitField0_ |= 0x00000001;
                success_ = input.readInt32();
                break;
              }
              case 16: {
                bitField0_ |= 0x00000002;
                executionTime_ = input.readInt32();
                break;
              }
              case 24: {
                bitField0_ |= 0x00000004;
                memoryUsed_ = input.readInt32();
                break;
              }
            }
          }
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(this);
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(
              e.getMessage()).setUnfinishedMessage(this);
        } finally {
          this.unknownFields = unknownFields.build();
          makeExtensionsImmutable();
        }
      }
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.nwchecker.server.utils.messages.CheckerResponseProto.internal_static_messages_CheckerResponse_AtomicResponse_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.nwchecker.server.utils.messages.CheckerResponseProto.internal_static_messages_CheckerResponse_AtomicResponse_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.nwchecker.server.utils.messages.CheckerResponseProto.CheckerResponse.AtomicResponse.class, com.nwchecker.server.utils.messages.CheckerResponseProto.CheckerResponse.AtomicResponse.Builder.class);
      }

      public static com.google.protobuf.Parser<AtomicResponse> PARSER =
          new com.google.protobuf.AbstractParser<AtomicResponse>() {
        public AtomicResponse parsePartialFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
          return new AtomicResponse(input, extensionRegistry);
        }
      };

      @java.lang.Override
      public com.google.protobuf.Parser<AtomicResponse> getParserForType() {
        return PARSER;
      }

      private int bitField0_;
      // required int32 success = 1;
      public static final int SUCCESS_FIELD_NUMBER = 1;
      private int success_;
      /**
       * <code>required int32 success = 1;</code>
       */
      public boolean hasSuccess() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required int32 success = 1;</code>
       */
      public int getSuccess() {
        return success_;
      }

      // required int32 executionTime = 2;
      public static final int EXECUTIONTIME_FIELD_NUMBER = 2;
      private int executionTime_;
      /**
       * <code>required int32 executionTime = 2;</code>
       */
      public boolean hasExecutionTime() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required int32 executionTime = 2;</code>
       */
      public int getExecutionTime() {
        return executionTime_;
      }

      // required int32 memoryUsed = 3;
      public static final int MEMORYUSED_FIELD_NUMBER = 3;
      private int memoryUsed_;
      /**
       * <code>required int32 memoryUsed = 3;</code>
       */
      public boolean hasMemoryUsed() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>required int32 memoryUsed = 3;</code>
       */
      public int getMemoryUsed() {
        return memoryUsed_;
      }

      private void initFields() {
        success_ = 0;
        executionTime_ = 0;
        memoryUsed_ = 0;
      }
      private byte memoizedIsInitialized = -1;
      public final boolean isInitialized() {
        byte isInitialized = memoizedIsInitialized;
        if (isInitialized != -1) return isInitialized == 1;

        if (!hasSuccess()) {
          memoizedIsInitialized = 0;
          return false;
        }
        if (!hasExecutionTime()) {
          memoizedIsInitialized = 0;
          return false;
        }
        if (!hasMemoryUsed()) {
          memoizedIsInitialized = 0;
          return false;
        }
        memoizedIsInitialized = 1;
        return true;
      }

      public void writeTo(com.google.protobuf.CodedOutputStream output)
                          throws java.io.IOException {
        getSerializedSize();
        if (((bitField0_ & 0x00000001) == 0x00000001)) {
          output.writeInt32(1, success_);
        }
        if (((bitField0_ & 0x00000002) == 0x00000002)) {
          output.writeInt32(2, executionTime_);
        }
        if (((bitField0_ & 0x00000004) == 0x00000004)) {
          output.writeInt32(3, memoryUsed_);
        }
        getUnknownFields().writeTo(output);
      }

      private int memoizedSerializedSize = -1;
      public int getSerializedSize() {
        int size = memoizedSerializedSize;
        if (size != -1) return size;

        size = 0;
        if (((bitField0_ & 0x00000001) == 0x00000001)) {
          size += com.google.protobuf.CodedOutputStream
            .computeInt32Size(1, success_);
        }
        if (((bitField0_ & 0x00000002) == 0x00000002)) {
          size += com.google.protobuf.CodedOutputStream
            .computeInt32Size(2, executionTime_);
        }
        if (((bitField0_ & 0x00000004) == 0x00000004)) {
          size += com.google.protobuf.CodedOutputStream
            .computeInt32Size(3, memoryUsed_);
        }
        size += getUnknownFields().getSerializedSize();
        memoizedSerializedSize = size;
        return size;
      }

      private static final long serialVersionUID = 0L;
      @java.lang.Override
      protected java.lang.Object writeReplace()
          throws java.io.ObjectStreamException {
        return super.writeReplace();
      }

      public static com.nwchecker.server.utils.messages.CheckerResponseProto.CheckerResponse.AtomicResponse parseFrom(
          com.google.protobuf.ByteString data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static com.nwchecker.server.utils.messages.CheckerResponseProto.CheckerResponse.AtomicResponse parseFrom(
          com.google.protobuf.ByteString data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static com.nwchecker.server.utils.messages.CheckerResponseProto.CheckerResponse.AtomicResponse parseFrom(byte[] data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static com.nwchecker.server.utils.messages.CheckerResponseProto.CheckerResponse.AtomicResponse parseFrom(
          byte[] data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static com.nwchecker.server.utils.messages.CheckerResponseProto.CheckerResponse.AtomicResponse parseFrom(java.io.InputStream input)
          throws java.io.IOException {
        return PARSER.parseFrom(input);
      }
      public static com.nwchecker.server.utils.messages.CheckerResponseProto.CheckerResponse.AtomicResponse parseFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return PARSER.parseFrom(input, extensionRegistry);
      }
      public static com.nwchecker.server.utils.messages.CheckerResponseProto.CheckerResponse.AtomicResponse parseDelimitedFrom(java.io.InputStream input)
          throws java.io.IOException {
        return PARSER.parseDelimitedFrom(input);
      }
      public static com.nwchecker.server.utils.messages.CheckerResponseProto.CheckerResponse.AtomicResponse parseDelimitedFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return PARSER.parseDelimitedFrom(input, extensionRegistry);
      }
      public static com.nwchecker.server.utils.messages.CheckerResponseProto.CheckerResponse.AtomicResponse parseFrom(
          com.google.protobuf.CodedInputStream input)
          throws java.io.IOException {
        return PARSER.parseFrom(input);
      }
      public static com.nwchecker.server.utils.messages.CheckerResponseProto.CheckerResponse.AtomicResponse parseFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return PARSER.parseFrom(input, extensionRegistry);
      }

      public static Builder newBuilder() { return Builder.create(); }
      public Builder newBuilderForType() { return newBuilder(); }
      public static Builder newBuilder(com.nwchecker.server.utils.messages.CheckerResponseProto.CheckerResponse.AtomicResponse prototype) {
        return newBuilder().mergeFrom(prototype);
      }
      public Builder toBuilder() { return newBuilder(this); }

      @java.lang.Override
      protected Builder newBuilderForType(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        Builder builder = new Builder(parent);
        return builder;
      }
      /**
       * Protobuf type {@code messages.CheckerResponse.AtomicResponse}
       */
      public static final class Builder extends
          com.google.protobuf.GeneratedMessage.Builder<Builder>
         implements com.nwchecker.server.utils.messages.CheckerResponseProto.CheckerResponse.AtomicResponseOrBuilder {
        public static final com.google.protobuf.Descriptors.Descriptor
            getDescriptor() {
          return com.nwchecker.server.utils.messages.CheckerResponseProto.internal_static_messages_CheckerResponse_AtomicResponse_descriptor;
        }

        protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
            internalGetFieldAccessorTable() {
          return com.nwchecker.server.utils.messages.CheckerResponseProto.internal_static_messages_CheckerResponse_AtomicResponse_fieldAccessorTable
              .ensureFieldAccessorsInitialized(
                  com.nwchecker.server.utils.messages.CheckerResponseProto.CheckerResponse.AtomicResponse.class, com.nwchecker.server.utils.messages.CheckerResponseProto.CheckerResponse.AtomicResponse.Builder.class);
        }

        // Construct using com.nwchecker.server.utils.messages.CheckerResponseProto.CheckerResponse.AtomicResponse.newBuilder()
        private Builder() {
          maybeForceBuilderInitialization();
        }

        private Builder(
            com.google.protobuf.GeneratedMessage.BuilderParent parent) {
          super(parent);
          maybeForceBuilderInitialization();
        }
        private void maybeForceBuilderInitialization() {
          if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          }
        }
        private static Builder create() {
          return new Builder();
        }

        public Builder clear() {
          super.clear();
          success_ = 0;
          bitField0_ = (bitField0_ & ~0x00000001);
          executionTime_ = 0;
          bitField0_ = (bitField0_ & ~0x00000002);
          memoryUsed_ = 0;
          bitField0_ = (bitField0_ & ~0x00000004);
          return this;
        }

        public Builder clone() {
          return create().mergeFrom(buildPartial());
        }

        public com.google.protobuf.Descriptors.Descriptor
            getDescriptorForType() {
          return com.nwchecker.server.utils.messages.CheckerResponseProto.internal_static_messages_CheckerResponse_AtomicResponse_descriptor;
        }

        public com.nwchecker.server.utils.messages.CheckerResponseProto.CheckerResponse.AtomicResponse getDefaultInstanceForType() {
          return com.nwchecker.server.utils.messages.CheckerResponseProto.CheckerResponse.AtomicResponse.getDefaultInstance();
        }

        public com.nwchecker.server.utils.messages.CheckerResponseProto.CheckerResponse.AtomicResponse build() {
          com.nwchecker.server.utils.messages.CheckerResponseProto.CheckerResponse.AtomicResponse result = buildPartial();
          if (!result.isInitialized()) {
            throw newUninitializedMessageException(result);
          }
          return result;
        }

        public com.nwchecker.server.utils.messages.CheckerResponseProto.CheckerResponse.AtomicResponse buildPartial() {
          com.nwchecker.server.utils.messages.CheckerResponseProto.CheckerResponse.AtomicResponse result = new com.nwchecker.server.utils.messages.CheckerResponseProto.CheckerResponse.AtomicResponse(this);
          int from_bitField0_ = bitField0_;
          int to_bitField0_ = 0;
          if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
            to_bitField0_ |= 0x00000001;
          }
          result.success_ = success_;
          if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
            to_bitField0_ |= 0x00000002;
          }
          result.executionTime_ = executionTime_;
          if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
            to_bitField0_ |= 0x00000004;
          }
          result.memoryUsed_ = memoryUsed_;
          result.bitField0_ = to_bitField0_;
          onBuilt();
          return result;
        }

        public Builder mergeFrom(com.google.protobuf.Message other) {
          if (other instanceof com.nwchecker.server.utils.messages.CheckerResponseProto.CheckerResponse.AtomicResponse) {
            return mergeFrom((com.nwchecker.server.utils.messages.CheckerResponseProto.CheckerResponse.AtomicResponse)other);
          } else {
            super.mergeFrom(other);
            return this;
          }
        }

        public Builder mergeFrom(com.nwchecker.server.utils.messages.CheckerResponseProto.CheckerResponse.AtomicResponse other) {
          if (other == com.nwchecker.server.utils.messages.CheckerResponseProto.CheckerResponse.AtomicResponse.getDefaultInstance()) return this;
          if (other.hasSuccess()) {
            setSuccess(other.getSuccess());
          }
          if (other.hasExecutionTime()) {
            setExecutionTime(other.getExecutionTime());
          }
          if (other.hasMemoryUsed()) {
            setMemoryUsed(other.getMemoryUsed());
          }
          this.mergeUnknownFields(other.getUnknownFields());
          return this;
        }

        public final boolean isInitialized() {
          if (!hasSuccess()) {
            
            return false;
          }
          if (!hasExecutionTime()) {
            
            return false;
          }
          if (!hasMemoryUsed()) {
            
            return false;
          }
          return true;
        }

        public Builder mergeFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
          com.nwchecker.server.utils.messages.CheckerResponseProto.CheckerResponse.AtomicResponse parsedMessage = null;
          try {
            parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
          } catch (com.google.protobuf.InvalidProtocolBufferException e) {
            parsedMessage = (com.nwchecker.server.utils.messages.CheckerResponseProto.CheckerResponse.AtomicResponse) e.getUnfinishedMessage();
            throw e;
          } finally {
            if (parsedMessage != null) {
              mergeFrom(parsedMessage);
            }
          }
          return this;
        }
        private int bitField0_;

        // required int32 success = 1;
        private int success_ ;
        /**
         * <code>required int32 success = 1;</code>
         */
        public boolean hasSuccess() {
          return ((bitField0_ & 0x00000001) == 0x00000001);
        }
        /**
         * <code>required int32 success = 1;</code>
         */
        public int getSuccess() {
          return success_;
        }
        /**
         * <code>required int32 success = 1;</code>
         */
        public Builder setSuccess(int value) {
          bitField0_ |= 0x00000001;
          success_ = value;
          onChanged();
          return this;
        }
        /**
         * <code>required int32 success = 1;</code>
         */
        public Builder clearSuccess() {
          bitField0_ = (bitField0_ & ~0x00000001);
          success_ = 0;
          onChanged();
          return this;
        }

        // required int32 executionTime = 2;
        private int executionTime_ ;
        /**
         * <code>required int32 executionTime = 2;</code>
         */
        public boolean hasExecutionTime() {
          return ((bitField0_ & 0x00000002) == 0x00000002);
        }
        /**
         * <code>required int32 executionTime = 2;</code>
         */
        public int getExecutionTime() {
          return executionTime_;
        }
        /**
         * <code>required int32 executionTime = 2;</code>
         */
        public Builder setExecutionTime(int value) {
          bitField0_ |= 0x00000002;
          executionTime_ = value;
          onChanged();
          return this;
        }
        /**
         * <code>required int32 executionTime = 2;</code>
         */
        public Builder clearExecutionTime() {
          bitField0_ = (bitField0_ & ~0x00000002);
          executionTime_ = 0;
          onChanged();
          return this;
        }

        // required int32 memoryUsed = 3;
        private int memoryUsed_ ;
        /**
         * <code>required int32 memoryUsed = 3;</code>
         */
        public boolean hasMemoryUsed() {
          return ((bitField0_ & 0x00000004) == 0x00000004);
        }
        /**
         * <code>required int32 memoryUsed = 3;</code>
         */
        public int getMemoryUsed() {
          return memoryUsed_;
        }
        /**
         * <code>required int32 memoryUsed = 3;</code>
         */
        public Builder setMemoryUsed(int value) {
          bitField0_ |= 0x00000004;
          memoryUsed_ = value;
          onChanged();
          return this;
        }
        /**
         * <code>required int32 memoryUsed = 3;</code>
         */
        public Builder clearMemoryUsed() {
          bitField0_ = (bitField0_ & ~0x00000004);
          memoryUsed_ = 0;
          onChanged();
          return this;
        }

        // @@protoc_insertion_point(builder_scope:messages.CheckerResponse.AtomicResponse)
      }

      static {
        defaultInstance = new AtomicResponse(true);
        defaultInstance.initFields();
      }

      // @@protoc_insertion_point(class_scope:messages.CheckerResponse.AtomicResponse)
    }

    // repeated .messages.CheckerResponse.AtomicResponse testData = 1;
    public static final int TESTDATA_FIELD_NUMBER = 1;
    private java.util.List<com.nwchecker.server.utils.messages.CheckerResponseProto.CheckerResponse.AtomicResponse> testData_;
    /**
     * <code>repeated .messages.CheckerResponse.AtomicResponse testData = 1;</code>
     */
    public java.util.List<com.nwchecker.server.utils.messages.CheckerResponseProto.CheckerResponse.AtomicResponse> getTestDataList() {
      return testData_;
    }
    /**
     * <code>repeated .messages.CheckerResponse.AtomicResponse testData = 1;</code>
     */
    public java.util.List<? extends com.nwchecker.server.utils.messages.CheckerResponseProto.CheckerResponse.AtomicResponseOrBuilder> 
        getTestDataOrBuilderList() {
      return testData_;
    }
    /**
     * <code>repeated .messages.CheckerResponse.AtomicResponse testData = 1;</code>
     */
    public int getTestDataCount() {
      return testData_.size();
    }
    /**
     * <code>repeated .messages.CheckerResponse.AtomicResponse testData = 1;</code>
     */
    public com.nwchecker.server.utils.messages.CheckerResponseProto.CheckerResponse.AtomicResponse getTestData(int index) {
      return testData_.get(index);
    }
    /**
     * <code>repeated .messages.CheckerResponse.AtomicResponse testData = 1;</code>
     */
    public com.nwchecker.server.utils.messages.CheckerResponseProto.CheckerResponse.AtomicResponseOrBuilder getTestDataOrBuilder(
        int index) {
      return testData_.get(index);
    }

    private void initFields() {
      testData_ = java.util.Collections.emptyList();
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      for (int i = 0; i < getTestDataCount(); i++) {
        if (!getTestData(i).isInitialized()) {
          memoizedIsInitialized = 0;
          return false;
        }
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      for (int i = 0; i < testData_.size(); i++) {
        output.writeMessage(1, testData_.get(i));
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      for (int i = 0; i < testData_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, testData_.get(i));
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static com.nwchecker.server.utils.messages.CheckerResponseProto.CheckerResponse parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.nwchecker.server.utils.messages.CheckerResponseProto.CheckerResponse parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.nwchecker.server.utils.messages.CheckerResponseProto.CheckerResponse parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.nwchecker.server.utils.messages.CheckerResponseProto.CheckerResponse parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.nwchecker.server.utils.messages.CheckerResponseProto.CheckerResponse parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.nwchecker.server.utils.messages.CheckerResponseProto.CheckerResponse parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.nwchecker.server.utils.messages.CheckerResponseProto.CheckerResponse parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.nwchecker.server.utils.messages.CheckerResponseProto.CheckerResponse parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.nwchecker.server.utils.messages.CheckerResponseProto.CheckerResponse parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.nwchecker.server.utils.messages.CheckerResponseProto.CheckerResponse parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.nwchecker.server.utils.messages.CheckerResponseProto.CheckerResponse prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code messages.CheckerResponse}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements com.nwchecker.server.utils.messages.CheckerResponseProto.CheckerResponseOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.nwchecker.server.utils.messages.CheckerResponseProto.internal_static_messages_CheckerResponse_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.nwchecker.server.utils.messages.CheckerResponseProto.internal_static_messages_CheckerResponse_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.nwchecker.server.utils.messages.CheckerResponseProto.CheckerResponse.class, com.nwchecker.server.utils.messages.CheckerResponseProto.CheckerResponse.Builder.class);
      }

      // Construct using com.nwchecker.server.utils.messages.CheckerResponseProto.CheckerResponse.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          getTestDataFieldBuilder();
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        if (testDataBuilder_ == null) {
          testData_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
        } else {
          testDataBuilder_.clear();
        }
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.nwchecker.server.utils.messages.CheckerResponseProto.internal_static_messages_CheckerResponse_descriptor;
      }

      public com.nwchecker.server.utils.messages.CheckerResponseProto.CheckerResponse getDefaultInstanceForType() {
        return com.nwchecker.server.utils.messages.CheckerResponseProto.CheckerResponse.getDefaultInstance();
      }

      public com.nwchecker.server.utils.messages.CheckerResponseProto.CheckerResponse build() {
        com.nwchecker.server.utils.messages.CheckerResponseProto.CheckerResponse result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.nwchecker.server.utils.messages.CheckerResponseProto.CheckerResponse buildPartial() {
        com.nwchecker.server.utils.messages.CheckerResponseProto.CheckerResponse result = new com.nwchecker.server.utils.messages.CheckerResponseProto.CheckerResponse(this);
        int from_bitField0_ = bitField0_;
        if (testDataBuilder_ == null) {
          if (((bitField0_ & 0x00000001) == 0x00000001)) {
            testData_ = java.util.Collections.unmodifiableList(testData_);
            bitField0_ = (bitField0_ & ~0x00000001);
          }
          result.testData_ = testData_;
        } else {
          result.testData_ = testDataBuilder_.build();
        }
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.nwchecker.server.utils.messages.CheckerResponseProto.CheckerResponse) {
          return mergeFrom((com.nwchecker.server.utils.messages.CheckerResponseProto.CheckerResponse)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.nwchecker.server.utils.messages.CheckerResponseProto.CheckerResponse other) {
        if (other == com.nwchecker.server.utils.messages.CheckerResponseProto.CheckerResponse.getDefaultInstance()) return this;
        if (testDataBuilder_ == null) {
          if (!other.testData_.isEmpty()) {
            if (testData_.isEmpty()) {
              testData_ = other.testData_;
              bitField0_ = (bitField0_ & ~0x00000001);
            } else {
              ensureTestDataIsMutable();
              testData_.addAll(other.testData_);
            }
            onChanged();
          }
        } else {
          if (!other.testData_.isEmpty()) {
            if (testDataBuilder_.isEmpty()) {
              testDataBuilder_.dispose();
              testDataBuilder_ = null;
              testData_ = other.testData_;
              bitField0_ = (bitField0_ & ~0x00000001);
              testDataBuilder_ = 
                com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                   getTestDataFieldBuilder() : null;
            } else {
              testDataBuilder_.addAllMessages(other.testData_);
            }
          }
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        for (int i = 0; i < getTestDataCount(); i++) {
          if (!getTestData(i).isInitialized()) {
            
            return false;
          }
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.nwchecker.server.utils.messages.CheckerResponseProto.CheckerResponse parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.nwchecker.server.utils.messages.CheckerResponseProto.CheckerResponse) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // repeated .messages.CheckerResponse.AtomicResponse testData = 1;
      private java.util.List<com.nwchecker.server.utils.messages.CheckerResponseProto.CheckerResponse.AtomicResponse> testData_ =
        java.util.Collections.emptyList();
      private void ensureTestDataIsMutable() {
        if (!((bitField0_ & 0x00000001) == 0x00000001)) {
          testData_ = new java.util.ArrayList<com.nwchecker.server.utils.messages.CheckerResponseProto.CheckerResponse.AtomicResponse>(testData_);
          bitField0_ |= 0x00000001;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilder<
          com.nwchecker.server.utils.messages.CheckerResponseProto.CheckerResponse.AtomicResponse, com.nwchecker.server.utils.messages.CheckerResponseProto.CheckerResponse.AtomicResponse.Builder, com.nwchecker.server.utils.messages.CheckerResponseProto.CheckerResponse.AtomicResponseOrBuilder> testDataBuilder_;

      /**
       * <code>repeated .messages.CheckerResponse.AtomicResponse testData = 1;</code>
       */
      public java.util.List<com.nwchecker.server.utils.messages.CheckerResponseProto.CheckerResponse.AtomicResponse> getTestDataList() {
        if (testDataBuilder_ == null) {
          return java.util.Collections.unmodifiableList(testData_);
        } else {
          return testDataBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .messages.CheckerResponse.AtomicResponse testData = 1;</code>
       */
      public int getTestDataCount() {
        if (testDataBuilder_ == null) {
          return testData_.size();
        } else {
          return testDataBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .messages.CheckerResponse.AtomicResponse testData = 1;</code>
       */
      public com.nwchecker.server.utils.messages.CheckerResponseProto.CheckerResponse.AtomicResponse getTestData(int index) {
        if (testDataBuilder_ == null) {
          return testData_.get(index);
        } else {
          return testDataBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .messages.CheckerResponse.AtomicResponse testData = 1;</code>
       */
      public Builder setTestData(
          int index, com.nwchecker.server.utils.messages.CheckerResponseProto.CheckerResponse.AtomicResponse value) {
        if (testDataBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureTestDataIsMutable();
          testData_.set(index, value);
          onChanged();
        } else {
          testDataBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .messages.CheckerResponse.AtomicResponse testData = 1;</code>
       */
      public Builder setTestData(
          int index, com.nwchecker.server.utils.messages.CheckerResponseProto.CheckerResponse.AtomicResponse.Builder builderForValue) {
        if (testDataBuilder_ == null) {
          ensureTestDataIsMutable();
          testData_.set(index, builderForValue.build());
          onChanged();
        } else {
          testDataBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .messages.CheckerResponse.AtomicResponse testData = 1;</code>
       */
      public Builder addTestData(com.nwchecker.server.utils.messages.CheckerResponseProto.CheckerResponse.AtomicResponse value) {
        if (testDataBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureTestDataIsMutable();
          testData_.add(value);
          onChanged();
        } else {
          testDataBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .messages.CheckerResponse.AtomicResponse testData = 1;</code>
       */
      public Builder addTestData(
          int index, com.nwchecker.server.utils.messages.CheckerResponseProto.CheckerResponse.AtomicResponse value) {
        if (testDataBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureTestDataIsMutable();
          testData_.add(index, value);
          onChanged();
        } else {
          testDataBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .messages.CheckerResponse.AtomicResponse testData = 1;</code>
       */
      public Builder addTestData(
          com.nwchecker.server.utils.messages.CheckerResponseProto.CheckerResponse.AtomicResponse.Builder builderForValue) {
        if (testDataBuilder_ == null) {
          ensureTestDataIsMutable();
          testData_.add(builderForValue.build());
          onChanged();
        } else {
          testDataBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .messages.CheckerResponse.AtomicResponse testData = 1;</code>
       */
      public Builder addTestData(
          int index, com.nwchecker.server.utils.messages.CheckerResponseProto.CheckerResponse.AtomicResponse.Builder builderForValue) {
        if (testDataBuilder_ == null) {
          ensureTestDataIsMutable();
          testData_.add(index, builderForValue.build());
          onChanged();
        } else {
          testDataBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .messages.CheckerResponse.AtomicResponse testData = 1;</code>
       */
      public Builder addAllTestData(
          java.lang.Iterable<? extends com.nwchecker.server.utils.messages.CheckerResponseProto.CheckerResponse.AtomicResponse> values) {
        if (testDataBuilder_ == null) {
          ensureTestDataIsMutable();
          super.addAll(values, testData_);
          onChanged();
        } else {
          testDataBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .messages.CheckerResponse.AtomicResponse testData = 1;</code>
       */
      public Builder clearTestData() {
        if (testDataBuilder_ == null) {
          testData_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
          onChanged();
        } else {
          testDataBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .messages.CheckerResponse.AtomicResponse testData = 1;</code>
       */
      public Builder removeTestData(int index) {
        if (testDataBuilder_ == null) {
          ensureTestDataIsMutable();
          testData_.remove(index);
          onChanged();
        } else {
          testDataBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .messages.CheckerResponse.AtomicResponse testData = 1;</code>
       */
      public com.nwchecker.server.utils.messages.CheckerResponseProto.CheckerResponse.AtomicResponse.Builder getTestDataBuilder(
          int index) {
        return getTestDataFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .messages.CheckerResponse.AtomicResponse testData = 1;</code>
       */
      public com.nwchecker.server.utils.messages.CheckerResponseProto.CheckerResponse.AtomicResponseOrBuilder getTestDataOrBuilder(
          int index) {
        if (testDataBuilder_ == null) {
          return testData_.get(index);  } else {
          return testDataBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .messages.CheckerResponse.AtomicResponse testData = 1;</code>
       */
      public java.util.List<? extends com.nwchecker.server.utils.messages.CheckerResponseProto.CheckerResponse.AtomicResponseOrBuilder> 
           getTestDataOrBuilderList() {
        if (testDataBuilder_ != null) {
          return testDataBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(testData_);
        }
      }
      /**
       * <code>repeated .messages.CheckerResponse.AtomicResponse testData = 1;</code>
       */
      public com.nwchecker.server.utils.messages.CheckerResponseProto.CheckerResponse.AtomicResponse.Builder addTestDataBuilder() {
        return getTestDataFieldBuilder().addBuilder(
            com.nwchecker.server.utils.messages.CheckerResponseProto.CheckerResponse.AtomicResponse.getDefaultInstance());
      }
      /**
       * <code>repeated .messages.CheckerResponse.AtomicResponse testData = 1;</code>
       */
      public com.nwchecker.server.utils.messages.CheckerResponseProto.CheckerResponse.AtomicResponse.Builder addTestDataBuilder(
          int index) {
        return getTestDataFieldBuilder().addBuilder(
            index, com.nwchecker.server.utils.messages.CheckerResponseProto.CheckerResponse.AtomicResponse.getDefaultInstance());
      }
      /**
       * <code>repeated .messages.CheckerResponse.AtomicResponse testData = 1;</code>
       */
      public java.util.List<com.nwchecker.server.utils.messages.CheckerResponseProto.CheckerResponse.AtomicResponse.Builder> 
           getTestDataBuilderList() {
        return getTestDataFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilder<
          com.nwchecker.server.utils.messages.CheckerResponseProto.CheckerResponse.AtomicResponse, com.nwchecker.server.utils.messages.CheckerResponseProto.CheckerResponse.AtomicResponse.Builder, com.nwchecker.server.utils.messages.CheckerResponseProto.CheckerResponse.AtomicResponseOrBuilder> 
          getTestDataFieldBuilder() {
        if (testDataBuilder_ == null) {
          testDataBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
              com.nwchecker.server.utils.messages.CheckerResponseProto.CheckerResponse.AtomicResponse, com.nwchecker.server.utils.messages.CheckerResponseProto.CheckerResponse.AtomicResponse.Builder, com.nwchecker.server.utils.messages.CheckerResponseProto.CheckerResponse.AtomicResponseOrBuilder>(
                  testData_,
                  ((bitField0_ & 0x00000001) == 0x00000001),
                  getParentForChildren(),
                  isClean());
          testData_ = null;
        }
        return testDataBuilder_;
      }

      // @@protoc_insertion_point(builder_scope:messages.CheckerResponse)
    }

    static {
      defaultInstance = new CheckerResponse(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:messages.CheckerResponse)
  }

  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_messages_CheckerResponse_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_messages_CheckerResponse_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_messages_CheckerResponse_AtomicResponse_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_messages_CheckerResponse_AtomicResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\025CheckerResponse.proto\022\010messages\"\233\001\n\017Ch" +
      "eckerResponse\022:\n\010testData\030\001 \003(\0132(.messag" +
      "es.CheckerResponse.AtomicResponse\032L\n\016Ato" +
      "micResponse\022\017\n\007success\030\001 \002(\005\022\025\n\rexecutio" +
      "nTime\030\002 \002(\005\022\022\n\nmemoryUsed\030\003 \002(\005B;\n#com.n" +
      "wchecker.server.utils.messagesB\024CheckerR" +
      "esponseProto"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_messages_CheckerResponse_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_messages_CheckerResponse_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_messages_CheckerResponse_descriptor,
              new java.lang.String[] { "TestData", });
          internal_static_messages_CheckerResponse_AtomicResponse_descriptor =
            internal_static_messages_CheckerResponse_descriptor.getNestedTypes().get(0);
          internal_static_messages_CheckerResponse_AtomicResponse_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_messages_CheckerResponse_AtomicResponse_descriptor,
              new java.lang.String[] { "Success", "ExecutionTime", "MemoryUsed", });
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }

  // @@protoc_insertion_point(outer_class_scope)
}
